### ISSUE TITLE
Jailee Quits, returns to Spawn.

### ISSUE THREAD

**Issue by waldfelt** [lexi-lambda/SimpleJail#6]
Dear SimpleJail,

After a what we call a revoke, the player is deprived of all permissions and is placed in jail. If the jailee logs out and logs in, he is sent to spawn. How come?

Greetings,
Waldfelt
(ef-clan.com)

**Comment by lexi-lambda** [comment]
I have no idea what the problem could be here. I'm assuming you've set your jail and unjail points using /setjail and /setunjail, respectively. Are there any other plugins that could be affecting a player's log in position?

**Comment by Mitsugaru** [comment]
If you're using MultiVerse, its probably the culprit :\

My fork has the same issue, which I only learned of recently.

Apparently, MultiVerse has an API of sorts to hook into... but I haven't had a look at it. Have you looked into MV @imjake9 ?

**Comment by lexi-lambda** [comment]
@Mitsugaru 
Hmm, interesting. I don't really see what could be causing the problem here since MV is just using the same event system as the rest of us, and it's not too complicated. Until I can do some testing, I wouldn't know for sure. What sounds like the problem, though, is this bit right here in the MV code:

``` java
if (this.plugin.getMVConfig().getEnforceAccess() // check this only if we're enforcing access!
        && !this.plugin.getMVPerms().hasPermission(p, "multiverse.access." + p.getWorld().getName(), false)) {
    p.sendMessage("[MV] - Sorry you can't be in this world anymore!");
    this.sendPlayerToDefaultWorld(p);
}
```

What seems to be happening is this: for whatever reason (possibly through the use of the `-*` node in something like PermissionsEX), the players in the jailed groups don't have the `multiverse.access` permission for the world the jail resides in. I can't be sure if that's the case, but it seems the only possibility.

**Comment by Mitsugaru** [comment]
@imjake9 
When I say I had the same issue, I meant that one server with a highly modified config for their multi verse setup had told me of this. Honestly, I couldn't reproduce the issue from a fresh config, only from theirs... and I didn't look for whatever flag was causing it. :/

I'll check their permissions later and see if that was causing it. Thanks for the reference point. I'd be happy if you are right.

**Comment by lexi-lambda** [comment]
@Mitsugaru 
That actually makes sense, since the enforce access flag would have to be set, and I don't believe that it's set to true by default (though I'm not totally sure).

Actually, scratch that, I just checked. It's set to false by default, so that definitely seems to be the issue. I guess the question becomes do we tell our users to fix their permissions or do we code something into the plugins to prevent the issue itself? I'm tempted to do the former, simply to reduce complexity (it's _Simple_ Jail after all), but I haven't decided.

**Comment by Mitsugaru** [comment]
@imjake9
Haha, nope. If it can be handled by permissions, then let it be. I was avoiding having to hook into multi verse for this one thing.

Also, how goes the revamp to SimpleJailCells?

**Comment by lexi-lambda** [comment]
@Mitsugaru 
Alrighty, then. That is that.

As for SimpleJailCells progress (and the SimpleJail plugin API), progress is slow. Mostly just because I have so little time to work on it these days. I know what I need to do for the most part, I just need to sit down and do it. I'm hoping to get to it soon, but I really have no idea when it'll be done. Thanks again for your support, your plugin seems pretty awesome. I'm proud to have such a fork! :D

Anyway, this is closed. Fix your config or your permission, take your pick.
